site_name: Xiangqigame
nav:
- Home: index.md
- Installing: installing.md
- Running: running.md
- Game Rules and Notation: notation.md
- Rules: implemented_rules.md
- Design and Implementation Details: implementation_details.md
# - Analyzing Game Data: analyzing_game_data.md

theme:
    name: readthedocs
