services:
  cpyenv:
    image: cpyenv
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        - username=${USER}
        - user_uid=${UID}
        - user_gid=${GID}
    container_name: cpyenv
    entrypoint: [ "/bin/bash", "/usr/local/bin/entrypoint.sh"]
    volumes:
      - ../:/home/${USER}/workspace/project
      - ./.vscode/:/home/${USER}/workspace/.vscode
      - /etc/localtime:/etc/localtime:ro
      # - ./.vscode_local_placeholder/:/home/${USER}/workspace/project/.vscode:ro
    ports:
      - "2201:22"
    init: true
    stdin_open: true
    tty: true

