var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "board_data_structs.hpp", "board__data__structs_8hpp.html", "board__data__structs_8hpp" ],
    [ "board_state_summarizer_interface.hpp", "board__state__summarizer__interface_8hpp.html", "board__state__summarizer__interface_8hpp" ],
    [ "evaluator_data_structs.hpp", "evaluator__data__structs_8hpp.html", "evaluator__data__structs_8hpp" ],
    [ "game_board.hpp", "game__board_8hpp.html", "game__board_8hpp" ],
    [ "game_piece.hpp", "game__piece_8hpp.html", "game__piece_8hpp" ],
    [ "hash_calculator.hpp", "hash__calculator_8hpp.html", "hash__calculator_8hpp" ],
    [ "json_utility_interface.hpp", "json__utility__interface_8hpp.html", "json__utility__interface_8hpp" ],
    [ "json_utility_nlohmann.hpp", "json__utility__nlohmann_8hpp.html", "json__utility__nlohmann_8hpp" ],
    [ "key_generator.hpp", "key__generator_8hpp.html", "key__generator_8hpp" ],
    [ "move_calculator.hpp", "move__calculator_8hpp.html", "move__calculator_8hpp" ],
    [ "move_calculator_details.hpp", "move__calculator__details_8hpp.html", "move__calculator__details_8hpp" ],
    [ "move_data_structs.hpp", "move__data__structs_8hpp.html", "move__data__structs_8hpp" ],
    [ "move_evaluator_interface.hpp", "move__evaluator__interface_8hpp.html", "move__evaluator__interface_8hpp" ],
    [ "move_evaluators.hpp", "move__evaluators_8hpp.html", "move__evaluators_8hpp" ],
    [ "piece_moves.hpp", "piece__moves_8hpp.html", "piece__moves_8hpp" ],
    [ "piece_points_bpo.hpp", "piece__points__bpo_8hpp.html", "piece__points__bpo_8hpp" ],
    [ "piece_points_data_structs.hpp", "piece__points__data__structs_8hpp.html", "piece__points__data__structs_8hpp" ],
    [ "piece_position_points.hpp", "piece__position__points_8hpp.html", "piece__position__points_8hpp" ],
    [ "piece_value_provider_interface.hpp", "piece__value__provider__interface_8hpp.html", "piece__value__provider__interface_8hpp" ],
    [ "space_info_provider_interface.hpp", "space__info__provider__interface_8hpp.html", "space__info__provider__interface_8hpp" ],
    [ "utility_functs.hpp", "utility__functs_8hpp.html", "utility__functs_8hpp" ],
    [ "zobrist.hpp", "zobrist_8hpp.html", "zobrist_8hpp" ]
];