var dir_46e67b79a66d4e1bea97ac4ccddce80e =
[
    [ "handlers", "dir_d23568a9ac51262829f6b983163adc67.html", "dir_d23568a9ac51262829f6b983163adc67" ],
    [ "__init__.py", "____init_____8py.html", null ],
    [ "__main__.py", "____main_____8py.html", "____main_____8py" ],
    [ "app.py", "app_8py.html", "app_8py" ],
    [ "app_new.py", "app__new_8py.html", "app__new_8py" ],
    [ "binding_type_unions.py", "binding__type__unions_8py.html", "binding__type__unions_8py" ],
    [ "command_input.py", "command__input_8py.html", "command__input_8py" ],
    [ "core_dataclass_mirrors.py", "core__dataclass__mirrors_8py.html", "core__dataclass__mirrors_8py" ],
    [ "enums.py", "enums_8py.html", "enums_8py" ],
    [ "game.py", "game_8py.html", "game_8py" ],
    [ "game_interfaces.py", "game__interfaces_8py.html", "game__interfaces_8py" ],
    [ "game_output_generator.py", "game__output__generator_8py.html", "game__output__generator_8py" ],
    [ "game_summary.py", "game__summary_8py.html", "game__summary_8py" ],
    [ "game_summary_io.py", "game__summary__io_8py.html", "game__summary__io_8py" ],
    [ "game_summary_plot_manager.py", "game__summary__plot__manager_8py.html", "game__summary__plot__manager_8py" ],
    [ "game_summary_plotters.py", "game__summary__plotters_8py.html", "game__summary__plotters_8py" ],
    [ "move_translator.py", "move__translator_8py.html", "move__translator_8py" ],
    [ "piece_info_extractor.py", "piece__info__extractor_8py.html", "piece__info__extractor_8py" ],
    [ "piece_points.py", "piece__points_8py.html", "piece__points_8py" ],
    [ "player_builder.py", "player__builder_8py.html", "player__builder_8py" ],
    [ "player_builder_new.py", "player__builder__new_8py.html", "player__builder__new_8py" ],
    [ "player_summary.py", "player__summary_8py.html", "player__summary_8py" ],
    [ "players.py", "players_8py.html", "players_8py" ],
    [ "terminal_output.py", "terminal__output_8py.html", "terminal__output_8py" ]
];