# add_subdirectory(src/core/board_components)
add_subdirectory(src/core/board_utilities)
add_subdirectory(src/core/common)
add_subdirectory(src/core/game_board)
add_subdirectory(src/core/hash_calculator)
add_subdirectory(src/core/json_interface)
add_subdirectory(src/core/json_internal)
add_subdirectory(src/core/json_io)
add_subdirectory(src/core/json_validation)
add_subdirectory(src/core/points_containers)
add_subdirectory(src/core/move_evaluators)
add_subdirectory(src/core/move_calculator)
add_subdirectory(src/core/piece_moves)
add_subdirectory(src/core/piece_points)
add_subdirectory(src/core/piece_points_spec)
add_subdirectory(src/core/utility_functs)
add_subdirectory(src/bindings)
add_subdirectory(tests/core)

if(NOT SKBUILD)
    add_subdirectory(src/data)
endif()